-- DDL: все изменения схемы выполняются при первом создании тома PostgreSQL.
CREATE TABLE teachers (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 full_name varchar(150) NOT NULL CHECK (length(trim(full_name)) > 0),
 department varchar(150) NOT NULL, position varchar(100) NOT NULL,
 degree varchar(100) NOT NULL, contacts varchar(200) NOT NULL
);
CREATE TABLE groups (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(40) NOT NULL UNIQUE, specialty varchar(150) NOT NULL,
 course integer NOT NULL CHECK(course BETWEEN 1 AND 6),
 study_mode varchar(20) NOT NULL CHECK(study_mode IN ('очная','заочная','очно-заочная')),
 intake_year integer NOT NULL CHECK(intake_year BETWEEN 2000 AND 2100),
 curator_id integer REFERENCES teachers(id) ON DELETE RESTRICT
);
CREATE TABLE students (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 full_name varchar(150) NOT NULL CHECK(length(trim(full_name)) > 0),
 birth_date date NOT NULL CHECK(birth_date >= '1900-01-01'),
 gender varchar(10) NOT NULL CHECK(gender IN ('мужской','женский')),
 contacts varchar(200) NOT NULL, group_id integer NOT NULL REFERENCES groups(id) ON DELETE RESTRICT,
 funding varchar(10) NOT NULL CHECK(funding IN ('бюджет','контракт')),
 admission_date date NOT NULL, status varchar(30) NOT NULL CHECK(status IN ('учится','академический отпуск','отчислен')),
 CHECK(birth_date < admission_date)
);
CREATE TABLE disciplines (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(150) NOT NULL UNIQUE, description text NOT NULL,
 lecture_hours integer NOT NULL CHECK(lecture_hours >= 0),
 practice_hours integer NOT NULL CHECK(practice_hours >= 0),
 lab_hours integer NOT NULL CHECK(lab_hours >= 0),
 control_form varchar(20) NOT NULL CHECK(control_form IN ('экзамен','зачет','курсовая'))
);
CREATE TABLE assignments (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 group_id integer NOT NULL REFERENCES groups(id) ON DELETE RESTRICT,
 discipline_id integer NOT NULL REFERENCES disciplines(id) ON DELETE RESTRICT,
 teacher_id integer NOT NULL REFERENCES teachers(id) ON DELETE RESTRICT,
 semester integer NOT NULL CHECK(semester BETWEEN 1 AND 12),
 academic_year integer NOT NULL CHECK(academic_year BETWEEN 2000 AND 2100),
 UNIQUE(group_id,discipline_id,semester,academic_year)
);
CREATE TABLE assessments (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 assignment_id integer NOT NULL REFERENCES assignments(id) ON DELETE RESTRICT,
 title varchar(150) NOT NULL,
 kind varchar(20) NOT NULL CHECK(kind IN ('лабораторная','контрольная','курсовая','семестровая')),
 weight numeric(6,3) NOT NULL CHECK(weight > 0 AND weight <= 100),
 grading varchar(10) NOT NULL CHECK(grading IN ('балл','зачет')),
 UNIQUE(assignment_id,title)
);
CREATE TABLE grades (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id integer NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
 assessment_id integer NOT NULL REFERENCES assessments(id) ON DELETE RESTRICT,
 value numeric(1,0) NOT NULL CHECK(value IN (0,1,2,3,4,5)),
 comment varchar(300) NOT NULL DEFAULT '',
 UNIQUE(student_id,assessment_id)
);
-- Межтабличная проверка защищает данные и при прямом выполнении SQL.
CREATE FUNCTION check_grade() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE student_group integer; target_group integer; scale text;
BEGIN
 SELECT group_id INTO student_group FROM students WHERE id=NEW.student_id;
 SELECT a.group_id, t.grading INTO target_group,scale FROM assessments t JOIN assignments a ON a.id=t.assignment_id WHERE t.id=NEW.assessment_id;
 IF student_group IS DISTINCT FROM target_group THEN RAISE EXCEPTION 'Студент не принадлежит группе назначения' USING ERRCODE='23514'; END IF;
 IF (scale='балл' AND NEW.value NOT BETWEEN 2 AND 5) OR (scale='зачет' AND NEW.value NOT IN (0,1)) THEN RAISE EXCEPTION 'Оценка не соответствует шкале' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER grades_validate BEFORE INSERT OR UPDATE ON grades FOR EACH ROW EXECUTE FUNCTION check_grade();
-- Нельзя перепривязать историю к другой группе или шкале задним числом.
CREATE FUNCTION protect_history() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_TABLE_NAME='students' AND NEW.group_id<>OLD.group_id AND EXISTS(SELECT 1 FROM grades WHERE student_id=OLD.id) THEN RAISE EXCEPTION 'Сначала удалите оценки перед переводом студента' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER students_history BEFORE UPDATE ON students FOR EACH ROW EXECUTE FUNCTION protect_history();
CREATE TABLE users (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username varchar(50) NOT NULL UNIQUE,
 password_hash text NOT NULL,
 role varchar(12) NOT NULL CHECK(role IN ('admin','dean','teacher','student')),
 student_id integer UNIQUE REFERENCES students(id) ON DELETE RESTRICT,
 teacher_id integer UNIQUE REFERENCES teachers(id) ON DELETE RESTRICT,
 active boolean NOT NULL DEFAULT true,
 CHECK((role='student' AND student_id IS NOT NULL AND teacher_id IS NULL) OR
       (role='teacher' AND teacher_id IS NOT NULL AND student_id IS NULL) OR
       (role IN ('admin','dean') AND student_id IS NULL AND teacher_id IS NULL))
);
CREATE TABLE sessions (
 token_hash text PRIMARY KEY, user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 expires_at timestamptz NOT NULL DEFAULT now()+interval '8 hours'
);
CREATE TABLE audit_log (
 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 user_id integer REFERENCES users(id) ON DELETE SET NULL,
 action varchar(30) NOT NULL, entity varchar(40) NOT NULL, entity_id integer,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX grades_student_idx ON grades(student_id);
CREATE INDEX assignments_teacher_idx ON assignments(teacher_id);
CREATE INDEX assessments_assignment_idx ON assessments(assignment_id);
CREATE INDEX students_group_idx ON students(group_id);
-- Итог появляется только после заполнения всех работ назначения.
-- Пропуск не превращается в ноль, а фиксируется признаком incomplete.
CREATE VIEW results AS
SELECT s.id student_id, s.full_name, s.group_id, a.id assignment_id,
 a.discipline_id, d.name discipline, a.semester, a.academic_year,
 CASE WHEN count(g.id)=count(t.id) AND count(t.id)>0 THEN
 CASE WHEN d.control_form='зачет' THEN min(g.value)
 ELSE round(sum(g.value*t.weight)/nullif(sum(t.weight),0),0) END END AS final_grade,
 (count(g.id)<count(t.id) OR count(t.id)=0) AS incomplete,
 d.control_form
FROM students s JOIN assignments a ON a.group_id=s.group_id
JOIN disciplines d ON d.id=a.discipline_id
LEFT JOIN assessments t ON t.assignment_id=a.id
LEFT JOIN grades g ON g.student_id=s.id AND g.assessment_id=t.id
GROUP BY s.id,a.id,d.id;
CREATE TABLE login_attempts (key text NOT NULL, attempted_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX login_attempts_key_idx ON login_attempts(key);
-- Дополнительные проверки физической модели, включая прямое редактирование SQL.
CREATE FUNCTION protect_links() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_TABLE_NAME='assignments' THEN
  IF (NEW.group_id<>OLD.group_id OR NEW.discipline_id<>OLD.discipline_id) AND EXISTS(SELECT 1 FROM assessments WHERE assignment_id=OLD.id) THEN RAISE EXCEPTION 'Назначение содержит работы' USING ERRCODE='23514'; END IF;
 ELSIF TG_TABLE_NAME='assessments' THEN
  IF (NEW.assignment_id<>OLD.assignment_id OR NEW.grading<>OLD.grading) AND EXISTS(SELECT 1 FROM grades WHERE assessment_id=OLD.id) THEN RAISE EXCEPTION 'Работа содержит оценки' USING ERRCODE='23514'; END IF;
 ELSIF TG_TABLE_NAME='disciplines' THEN
  IF NEW.control_form<>OLD.control_form AND EXISTS(SELECT 1 FROM assignments WHERE discipline_id=OLD.id) THEN RAISE EXCEPTION 'Дисциплина назначена' USING ERRCODE='23514'; END IF;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER assignments_history BEFORE UPDATE ON assignments FOR EACH ROW EXECUTE FUNCTION protect_links();
CREATE TRIGGER assessments_history BEFORE UPDATE ON assessments FOR EACH ROW EXECUTE FUNCTION protect_links();
CREATE TRIGGER disciplines_history BEFORE UPDATE ON disciplines FOR EACH ROW EXECUTE FUNCTION protect_links();
CREATE FUNCTION check_scale() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE form text;
BEGIN
 SELECT d.control_form INTO form FROM assignments a JOIN disciplines d ON d.id=a.discipline_id WHERE a.id=NEW.assignment_id;
 IF (NEW.grading='зачет') IS DISTINCT FROM (form='зачет') THEN RAISE EXCEPTION 'Несовместимая шкала' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER assessments_scale BEFORE INSERT OR UPDATE ON assessments FOR EACH ROW EXECUTE FUNCTION check_scale();
